server:
  port: 7777
  shutdown: immediate

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: password
      driver-class-name: org.h2.Driver
      connection-test-query: SELECT 1

  flyway:
    cleanDisabled: false
    enabled: true
    locations: classpath:db/migration

  # Configuração do Console H2
  h2:
    console:
      enabled: true
      path: /h2-console
