server:
  port: 7777
  shutdown: immediate

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5443/funeraria_db
      username: funeraria_user
      password: funeraria_password
      connection-test-query: SELECT 1

  flyway:
    cleanDisabled: false
    enabled: true
    locations: classpath:db/migration

base_url: "http://localhost:8081/"