spring:
  datasource:
    hikari:
      jdbc-url: ${DATABASE_URL}
      username: ${USER}
      password: ${PASSWORD}
      connection-test-query: SELECT 1

base_url: ${BASE_URL}
base_url_external: ${BASE_URL_EXTERNAL}
