server:
  port: 8081

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5442/funeraria_db
      username: funeraria_user
      password: funeraria_password
      connection-test-query: SELECT 1
